# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import host_bridge_pb2 as host__bridge__pb2  # protoc emits an absolute
# import here by default, which breaks once this file lives inside the
# claudeops.proto package — hand-patched to relative after every regen
# (documented in proto/__init__.py so this isn't silently lost).

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in host_bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HostBridgeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/claudeops.hostbridge.v1.HostBridge/Ping',
                request_serializer=host__bridge__pb2.PingRequest.SerializeToString,
                response_deserializer=host__bridge__pb2.PingResponse.FromString,
                _registered_method=True)
        self.StreamStatus = channel.unary_stream(
                '/claudeops.hostbridge.v1.HostBridge/StreamStatus',
                request_serializer=host__bridge__pb2.StreamStatusRequest.SerializeToString,
                response_deserializer=host__bridge__pb2.StatusUpdate.FromString,
                _registered_method=True)
        self.StreamTermOutput = channel.unary_stream(
                '/claudeops.hostbridge.v1.HostBridge/StreamTermOutput',
                request_serializer=host__bridge__pb2.StreamTermOutputRequest.SerializeToString,
                response_deserializer=host__bridge__pb2.TermUpdate.FromString,
                _registered_method=True)


class HostBridgeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Capability-probe — sadece transport+auth+servicer'ın GERÇEKTEN çalıştığını
        kanıtlar (bkz. web_hosts.py'nin capability prober'ı — grpc.channel_ready_
        future() TEK BAŞINA sadece HTTP/2 handshake'ini kanıtlar, auth/servicer'ı
        değil; grpc_health.v1 standart protokolü de üçüncü bir bağımlılık olurdu,
        bu tek RPC'nin verdiğini zaten bedava veriyor).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamStatus(self, request, context):
        """web_hosts.py'nin arka plan poller'ının tekrar tekrar fetch_remote_status()
        çağırmasının yerini alır.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTermOutput(self, request, context):
        """web_ws.py'nin _term_poll_loop'unun REMOTE dalının (bugün web_hosts.
        proxy_get() tekrar tekrar çağırıyor) yerini alır.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HostBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=host__bridge__pb2.PingRequest.FromString,
                    response_serializer=host__bridge__pb2.PingResponse.SerializeToString,
            ),
            'StreamStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamStatus,
                    request_deserializer=host__bridge__pb2.StreamStatusRequest.FromString,
                    response_serializer=host__bridge__pb2.StatusUpdate.SerializeToString,
            ),
            'StreamTermOutput': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTermOutput,
                    request_deserializer=host__bridge__pb2.StreamTermOutputRequest.FromString,
                    response_serializer=host__bridge__pb2.TermUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'claudeops.hostbridge.v1.HostBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('claudeops.hostbridge.v1.HostBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HostBridge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/claudeops.hostbridge.v1.HostBridge/Ping',
            host__bridge__pb2.PingRequest.SerializeToString,
            host__bridge__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/claudeops.hostbridge.v1.HostBridge/StreamStatus',
            host__bridge__pb2.StreamStatusRequest.SerializeToString,
            host__bridge__pb2.StatusUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTermOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/claudeops.hostbridge.v1.HostBridge/StreamTermOutput',
            host__bridge__pb2.StreamTermOutputRequest.SerializeToString,
            host__bridge__pb2.TermUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
